// Turns results/balance-*.json into markdown tables (summary-balance.md): one table per configuration, then each egg against core.
// Usage: node prototype/netling2/baseline/summarize.mjs   (reads results/, writes summary-balance.md next to this file)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const load = (c) => JSON.parse(readFileSync(join(here, 'results', `balance-${c}.json`), 'utf8'));
const configs = ['core', 'full-iron', 'full-program', 'full-wetware'];
const data = Object.fromEntries(configs.map((c) => [c, load(c)]));

const pct = (v) => (v === undefined || v === null ? '-' : `${(v * 100).toFixed(1)}`);
const num = (d) => (v) => (v === undefined || v === null ? '-' : v.toFixed(d));
// Columns: [header, getter, formatter]. fullLife is the share of lives that reached the end of the life cycle.
const COLS = [
  ['full life %', (a) => a.fullLife, pct],
  ['median days', (a) => a.medianDays, num(1)],
  ['faults', (a) => a.mistakes, num(1)],
  ['bugs avg', (a) => a.bugs?.avg, num(2)],
  ['bug ceiling %', (a) => a.bugs?.atCeiling, pct],
  ['viruses', (a) => a.pressure?.viruses, num(1)],
  ['events', (a) => a.events, num(1)],
  ['netruns', (a) => a.netruns?.runs, num(1)],
  ['disconnects', (a) => a.netruns?.disconnects, num(2)],
  ['wins', (a) => a.wins, num(1)],
  ['scrip end', (a) => a.scrip?.end, num(0)],
  ['teen tie %', (a) => a.atTeen?.tied, pct],
  ['adult lean certain %', (a) => a.atAdult?.leanCertain, pct],
  ['baby d', (a) => a.stageDays?.baby, num(2)],
  ['teen d', (a) => a.stageDays?.teen, num(2)],
  ['adult d', (a) => a.stageDays?.adult, num(2)],
];
const names = Object.keys(data.core.archetypes);
const table = (cfg) => {
  const rows = [`| archetype | ${COLS.map((c) => c[0]).join(' | ')} |`, `|---|${COLS.map(() => '---:').join('|')}|`];
  for (const n of names) {
    const a = data[cfg].archetypes[n];
    rows.push(`| ${n} | ${COLS.map(([, g, f]) => f(g(a))).join(' | ')} |`);
  }
  return rows.join('\n');
};
// Egg minus core, full-life points and the movers by more than noise (1000 lives: about 1.5 points on a rate near 90%).
const diffTable = (cfg) => {
  const rows = ['| archetype | core full life % | ' + cfg + ' full life % | change (points) | faults change | bugs avg change | viruses change |', '|---|---:|---:|---:|---:|---:|---:|'];
  for (const n of names) {
    const a = data.core.archetypes[n];
    const b = data[cfg].archetypes[n];
    const d = (b.fullLife - a.fullLife) * 100;
    rows.push(`| ${n} | ${pct(a.fullLife)} | ${pct(b.fullLife)} | ${d >= 0 ? '+' : ''}${d.toFixed(1)} | ${(b.mistakes - a.mistakes).toFixed(1)} | ${((b.bugs?.avg ?? 0) - (a.bugs?.avg ?? 0)).toFixed(2)} | ${((b.pressure?.viruses ?? 0) - (a.pressure?.viruses ?? 0)).toFixed(1)} |`);
  }
  return rows.join('\n');
};
const out = [
  '# Balance baseline tables (generated)',
  '',
  `Generated by \`summarize.mjs\` from \`results/balance-*.json\`: ${data.core.runs} lives per archetype, ${names.length} archetypes. Do not edit by hand.`,
  '',
  ...configs.flatMap((c) => [`## ${c}`, '', table(c), '']),
  ...configs.slice(1).flatMap((c) => [`## ${c} against core`, '', diffTable(c), '']),
];
writeFileSync(join(here, 'summary-balance.md'), out.join('\n'));
console.log(`wrote summary-balance.md (${names.length} archetypes, ${configs.length} configurations)`);
